# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt:
        packages:
            - lib32stdc++6

# Set the build environment
env:
    - SMVERSION=1.9

# And compile!
install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - cd addons/sourcemod/scripting/
    - wget "https://raw.githubusercontent.com/TeamPotry/FF2_Fork/2.2/sourcemod/scripting/include/ff2_potry.inc" -O include/ff2_potry.inc
    - wget "https://raw.githubusercontent.com/TeamPotry/FF2_Fork/2.2/sourcemod/scripting/include/freak_fortress_2.inc" -O include/freak_fortress_2.inc
    - chmod +x spcomp
script:
    - ./compile.sh boss_selection.sp

# Notifications
notifications:
    email: false
