name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm-version: [ '1.10.x', '1.11.x', '1.11.6467']

    name: SM version ${{ matrix.sm-version }}
    steps:        
      - name: Setup SourceMod
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Setup Source
        uses: actions/checkout@master

      - name: Compile
        working-directory: addons/sourcemod/scripting
        run: |
          which spcomp
          echo $includePath
          spcomp -i$includePath boss_selection.sp -o output/boss_selection.smx  


      
