name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm-version: [ '1.10.x', '1.11.x', '1.11.6467']

    name: SM version ${{ matrix.sm-version }}
    steps:
      - uses: actions/checkout@v1

      - name: Setup
        uses: rumblefrog/setup-sp@master
        with:
          working-directory: addons/sourcemod/scripting
          version: ${{ matrix.sm-version }}

      - run: |
          which spcomp
          echo $includePath
          spcomp -i$includePath boss_selection.sp -o output/boss_selection.smx  


      
