name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm-version: [ '1.10.x', '1.11.x', '1.11.6467']

    name: SM version ${{ matrix.sm-version }}
    steps:        
      - name: Setup SourceMod
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Setup Source
        uses: actions/checkout@master
      
      - name: Setup Include
        working-directory: addons/sourcemod/scripting
        run: |             
          wget https://raw.githubusercontent.com/TeamPotry/FF2_Fork/master/sourcemod/scripting/include/freak_fortress_2.inc -P include
          wget https://raw.githubusercontent.com/TeamPotry/FF2_Fork/master/sourcemod/scripting/include/ff2_potry.inc -P include
          wget "http://www.doctormckay.com/download/scripting/include/morecolors.inc" -P include

      - name: Compile
        working-directory: addons/sourcemod/scripting
        run: |
          mkdir build
          
          spcomp boss_selection.sp -o build/boss_selection.smx
          rm ./include/ff2_potry.inc
          spcomp boss_selection.sp -o build/boss_selection_v1.smx


      
